# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HBO
  pod 'Firebase/Core'
  pod 'Firebase/Auth' 
  pod 'Firebase/Database'
  
  pod 'SwiftyJSON'
  pod 'Firebase/Storage'
  
  #pod 'Firebase/Firestore'
  
  pod 'Kingfisher', '~> 5.9'
  pod 'BiometricAuthentication'

  #Build failed on GoogleSignIn	
  #pod 'GoogleSignIn'
  
  target 'HBOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HBOUITests' do
    # Pods for testing
  end

end

