# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HBO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HBO

  target 'HBOTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HBOUITests' do
    # Pods for testing
  end

end

pod 'Firebase/Auth'
pod 'Firebase/Database'